spring:
  application:
    name: be-core
  threads:
    virtual:
      enabled: true

integrations:
  vault:
    url: ${VAULT_URL:http://vault:8200}
    role-id: ${VAULT_ROLE_ID}
    secret-id: ${VAULT_SECRET_ID}
    secret-root: ${VAULT_SECRET_ROOT:secrets}
  cache:
    api-key-current:
      expire-minutes: ${ATHOS_CACHES_API_KEY_CURRENT:3600}
    api-key-previous:
      expire-minutes: ${ATHOS_CACHES_API_KEY_PREVIOUS:900}
    gateway-address:
      expire-minutes: ${ATHOS_CACHES_GATEWAY_ADDRESS:3600}